version: '3.0.0'

services:
  #クライアントサイド設定
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    image: ih42casestudy-client
    container_name: ih42-client
    ports:
      - 3000:3000
    restart: always
    networks:
      - ih42-network
    volumes:
      - ./client:/app
      - ih42-client-node-modules:/app/node_modules

  #サーバーサイド設定
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    image: ih42casestudy-server
    container_name: ih42-server
    ports:
      - 4000:4000
      - 4001:4001
    restart: always
    networks:
      - ih42-network
      - ih42-network-server
    volumes:
      - ./server:/app
      - ih42-server-node-modules:/app/node_modules

#ネットワーク設定
networks:
  ih42-network:
    driver: bridge
  ih42-network-server:
    driver: bridge

#ボリューム設定
volumes:
  ih42-client-node-modules:
  ih42-server-node-modules: