version: '3.0.0'

services:
  #クライアントサイド設定
  client:
    build:
      context: ./
      image: ih42casestudy-client
      dockerfile: ./docker/client/Dockerfile
    container_name: ih42-client
    ports:
      - 3000:3000
    restart: always
    networks:
      - ih42-network
    volumes:
      - ./client:/app
      - ih42-client-node-modules:/app/node_modules

  #サーバーサイド設定
  server:
    build:
      context: ./
      image: ih42casestudy-server
      dockerfile: ./docker/server/Dockerfile
    container_name: ih42-server
    ports:
      - 4000:4000
    restart: always
    networks:
      - ih42-network
      - ih42-network-server
    volumes:
      - ./server:/app
      - ih42-server-node-modules:/app/node_modules

  #データベース設定
  database:
    build:
      image: ih42casestudy-database
      dockerfile: ./docker/database/Dockerfile
    container_name: ih42-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - ih42-network-server
    volumes:
      - ih42-database:/var/lib/mysql

#ネットワーク設定
networks:
  ih42-network:
    driver: bridge
  ih42-network-server:
    driver: bridge

#ボリューム設定
volumes:
  ih42-client-node-modules:
  ih42-server-node-modules:
  ih42-database: